# Generated by Django 4.2.11 on 2024-04-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0005_productdetailpage_description_multipleproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailpage',
            name='outer_description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='outer_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='outer_image',
            field=models.ForeignKey(blank=True, help_text='Homepage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='outer_title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
