# Generated by Django 4.2.11 on 2024-04-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('home', '0006_productdetailpage_outer_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantPage',
            new_name='ApplicationDetailPage',
        ),
        migrations.RenameModel(
            old_name='ApplicantDetailPage',
            new_name='ApplicationPage',
        ),
    ]
