# Generated by Django 4.2.11 on 2024-04-23 20:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0007_rename_applicantpage_applicationdetailpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetailpage',
            name='header_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdetailpage',
            name='left_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdetailpage',
            name='left_image',
            field=models.ForeignKey(blank=True, help_text='Homepage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='applicationdetailpage',
            name='middle_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdetailpage',
            name='outer_description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='applicationdetailpage',
            name='outer_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='applicationdetailpage',
            name='outer_image',
            field=models.ForeignKey(blank=True, help_text='Homepage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='applicationdetailpage',
            name='outer_title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='applicationdetailpage',
            name='right_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdetailpage',
            name='right_image',
            field=models.ForeignKey(blank=True, help_text='Homepage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='applicationpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
